[package]
name = "hft-domain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
anyhow = { workspace = true }
async-trait = "0.1"
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

